### ISSUE TITLE
Remove spawnCount from ParticleSpawner and move it to ParticleSpawner.spawn

### ISSUE THREAD

**Issue by KelianB** [KelianB/blapika-game-framework#13]

**Comment by Blatoy** [comment]
I'm not sure if it's a good idea to move it because a lot of ParticleSpawner will always spawn the same amount of particle but it may be a great idea to add it into the .spawn() without removing it from the ParticleSpawner configuration

**Comment by KelianB** [comment]
Implemented as described above: use ParticleSpawner.spawnCount or override it with ParticleSpawner.spawn({count: 10, ...}).
